name: CI_CD

on: [push]
jobs:
 job1:
  runs-on: ubuntu-latest
  name: checkout and run
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run hello
      run: python hello.py
 job2:
  runs-on: ubuntu-latest
  name: create archive
  needs: [job1]
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: archive
      uses: actions/upload-artifact@v2
      with: 
       name: hello
       path: .
      
 
